# repo branches

branches:
  only:
  - master

# job environment

sudo: false

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"

# job phases

install:
  - pip install --editable .[test]

script:
  - flake8 --count authors
  - pytest --cov --cov-report=term-missing

after_success:
  - coveralls
  
