# repo branches

branches:
  only:
  - master

# job environment

sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

# job phases

install:
  - pip install --editable .[test]

script:
  - radon mi --show authors
  - flake8 --count authors
  - py.test -vv --cov --cov-report=term-missing

after_success:
  - coveralls
  
